version: '3.8'

services:
  app:
    # ports:
    #   - 8443:8443
    image: wuming3019/zast-owasp-bm-java-runtime:v1
    restart: unless-stopped
    volumes:
      - ./:/owasp-mnt
  
  cloudflared:
    image: cloudflare/cloudflared:2025.9.1
    depends_on:
      - app
    command: tunnel --no-tls-verify --url https://app:8443
    restart: unless-stopped